name: pr-base-check

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main, develop]

jobs:
  check:
    uses: ShipFast-Syndicate/.github/.github/workflows/reusable-pr-base-check.yml@v0.1.2
