name: SonarCloud

on:
  push:
    branches: [main, develop]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'LICENSE'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    uses: ShipFast-Syndicate/.github/.github/workflows/reusable-sonar.yml@v0.1.0
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
